version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - app_network

  app:
    build: .
    networks:
      - app_network
    depends_on:
      - redis

networks:
  app_network:
    driver: bridge